server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_recruit?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tb_
  type-aliases-package: com.unbmy.recruit.pojo

